apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feast-serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-serving.name" . }}
    component: serving
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  store.yaml: |
{{- if index .Values "store.yaml" }}
{{- toYaml (index .Values "store.yaml") | nindent 4 }}
{{- else }}
    name: redis-store
    type: REDIS
    redis_config:
      host: {{ .Release.Name }}-redis-master
      port: 6379
    subscriptions:
    - name: "*"
      project: "*"
      version: "*"
{{- end }}

  application-default.yaml: |
    feast:
      core-host: {{ .Release.Name }}-feast-core
      store:
        config-path: /etc/feast/store.yaml
      jobs:
        store-type: REDIS
        store-options:
          host: {{ .Release.Name }}-redis-master
          port: 6379

  application-override.yaml: |
{{- toYaml (index .Values "application-override.yaml") | nindent 4 }}    
