apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "feast-core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-core.name" . }}
    component: core
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application-default-postgresql.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/postgres

  application-default-kafka.yaml: |
    feast:
      stream:
        type: kafka
        options: 
          bootstrapServers: {{ .Release.Name }}-kafka:9092
          topic: feast

  application-default-statsd.yaml: |
    feast:
      jobs:
        metrics:
          enabled: true 
          type: statsd
          host: {{ .Release.Name }}-prometheus-statsd-exporter-udp
          port: 9125

  application-override.yaml: |
{{- toYaml (index .Values "application-override.yaml") | nindent 4 }}    
