apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "feast-core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "feast-core.name" . }}
    component: core
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "feast-core.name" . }}
      component: core
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: {{ template "feast-core.name" . }}
        component: core
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: {{ template "feast-core.fullname" . }}-config
        configMap:
          name: {{ template "feast-core.fullname" . }}
      {{- if .Values.gcpServiceAccount.enabled }}
      - name: {{ template "feast-core.fullname" . }}-gcp-service-account
        secret:
          secretName: {{ .Values.gcpServiceAccount.existingSecret.name }}
      {{- end }}

      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        volumeMounts:
        - name: {{ template "feast-core.fullname" . }}-config
          mountPath: /etc/feast
        {{- if .Values.gcpServiceAccount.enabled }}
        - name: {{ template "feast-core.fullname" . }}-gcp-service-account
          mountPath: /etc/secrets/google
          readOnly: true
        {{- end }}

        env:
        - name: LOG_TYPE
          value: {{ .Values.logType | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
              key: postgresql-password

        {{- if .Values.gcpServiceAccount.enabled }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/google/{{ .Values.gcpServiceAccount.existingSecret.key }}
        {{- end }}

        {{- if .Values.gcpProjectId }}
        - name: GOOGLE_CLOUD_PROJECT
          value: {{ .Values.gcpProjectId | quote }}
        {{- end }}

        {{- if .Values.javaOpts }}
        - name: JAVA_OPTS
          value: {{ .Values.javaOpts }}
        {{- end }}

        command:
        - java 
        - -jar 
        - /opt/feast/feast-core.jar
        - --spring.config.additional-location=/etc/feast/application-default-postgresql.yaml,/etc/feast/application-default-kafka.yaml,/etc/feast/application-default-statsd.yaml,/etc/feast/application-override.yaml
        ports:
        - name: http
          containerPort: {{ .Values.service.http.targetPort }}
        - name: grpc
          containerPort: {{ .Values.service.grpc.targetPort }}

        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.http.targetPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}

        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.http.targetPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
